#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 19 14:28:38 2018

@author: k1461506
"""
import random 
import math 

class kMeans():
    
    def __init__(self, x, y):
        """
        :param x: x-coordinates of all points (list)
        :param y: y-coordinates of all points (list)
        """
        self.x = x 
        self.y = y
        
    def initializeCluster(self): # only creates two cluster cneters. 
        self.c1 = [randint(min(self.x,), max(self.x), randint(min(self.y), max(self.y))]
        self.c2 = [randint(min(self.x,), max(self.x), randint(min(self.y), max(self.y))]
        
        return self.c1, self.c2 # Returns integers that act as random cluster centers initially 
    
    def calcEuclidean(self, x1, y1, x2, y2):
        distance = math.sqrt((x1-x2)**2 + (y1-y2)**2) 
        
        return distance 
    
    def getCluster(self, x, y, c1, c2):
        
        